/****************************************************************************
Generated from F:\qcc5126\QCC5126\Earbuds1\apps\applications\earbud\qcc512x_rom_v21\CF376_CG814\dfu\dfu-public.key
by C:\qtil\ADK_QCC512X_ROM_V21_WIN_6.4.0.39\tools\gen_rsa_pss_constants.py
at 16:22:46 27/10/2019

FILE NAME
    rsa_pss_constants.c

DESCRIPTION
    Constant data needed for the rsa_decrypt and the ce_pkcs1_pss_padding_verify
    function.

NOTES
    The constant data for the rsa_decrypt is generated by the host from the
    RSA public key and compiled into the rsa_pss_constants library.
    It is directly related to the RSA private and public key pair, and if they
    change then this file must be regenerated from the public key.

****************************************************************************/

#include "rsa_decrypt.h"

/*
 * The const rsa_mod_t *mod parameter for the rsa_decrypt function.
 */
const rsa_mod_t rsa_decrypt_constant_mod = {
    /* uint16 M[RSA_SIGNATURE_SIZE] where RSA_SIGNATURE_SIZE is 128 */
    {
        0xd2a5,     /* 00 */
        0xb90c,     /* 01 */
        0x62ce,     /* 02 */
        0xce73,     /* 03 */
        0x2539,     /* 04 */
        0x8048,     /* 05 */
        0x5ea8,     /* 06 */
        0xe3e0,     /* 07 */
        0xae29,     /* 08 */
        0x50d6,     /* 09 */
        0xe16a,     /* 10 */
        0x39ce,     /* 11 */
        0x0969,     /* 12 */
        0x2c28,     /* 13 */
        0x1b6d,     /* 14 */
        0x8391,     /* 15 */
        0x94c6,     /* 16 */
        0xdc5f,     /* 17 */
        0x71ee,     /* 18 */
        0x0d17,     /* 19 */
        0xaf0b,     /* 20 */
        0x285d,     /* 21 */
        0xaf81,     /* 22 */
        0xe486,     /* 23 */
        0x1533,     /* 24 */
        0x85b2,     /* 25 */
        0xeea1,     /* 26 */
        0x847c,     /* 27 */
        0x8db9,     /* 28 */
        0xa241,     /* 29 */
        0xe69d,     /* 30 */
        0x6b01,     /* 31 */
        0x2b8e,     /* 32 */
        0x12da,     /* 33 */
        0xe94d,     /* 34 */
        0x9a5f,     /* 35 */
        0xf056,     /* 36 */
        0xd2ee,     /* 37 */
        0x8971,     /* 38 */
        0xe18c,     /* 39 */
        0x17d5,     /* 40 */
        0x8127,     /* 41 */
        0x3a60,     /* 42 */
        0x7df2,     /* 43 */
        0x5d38,     /* 44 */
        0xf1ba,     /* 45 */
        0x9265,     /* 46 */
        0xf0a3,     /* 47 */
        0x384d,     /* 48 */
        0x4fba,     /* 49 */
        0x8382,     /* 50 */
        0x2799,     /* 51 */
        0xa9ea,     /* 52 */
        0x7350,     /* 53 */
        0xb976,     /* 54 */
        0x793e,     /* 55 */
        0xa5b9,     /* 56 */
        0x52d5,     /* 57 */
        0x91e8,     /* 58 */
        0x0423,     /* 59 */
        0xf11a,     /* 60 */
        0xad1a,     /* 61 */
        0x586b,     /* 62 */
        0xe50c,     /* 63 */
        0x665e,     /* 64 */
        0xe524,     /* 65 */
        0xc490,     /* 66 */
        0x8ea2,     /* 67 */
        0x38c5,     /* 68 */
        0x4103,     /* 69 */
        0x5c87,     /* 70 */
        0x8746,     /* 71 */
        0xbc7f,     /* 72 */
        0x4a3a,     /* 73 */
        0x3b85,     /* 74 */
        0xc997,     /* 75 */
        0x7ca1,     /* 76 */
        0x2973,     /* 77 */
        0xb0c7,     /* 78 */
        0x2451,     /* 79 */
        0xe88d,     /* 80 */
        0x4017,     /* 81 */
        0x6dd1,     /* 82 */
        0x8048,     /* 83 */
        0x4fdd,     /* 84 */
        0x8fcd,     /* 85 */
        0x2363,     /* 86 */
        0x02a8,     /* 87 */
        0x4e73,     /* 88 */
        0xf774,     /* 89 */
        0xd784,     /* 90 */
        0x6a4f,     /* 91 */
        0xa726,     /* 92 */
        0xb3cd,     /* 93 */
        0x8b6d,     /* 94 */
        0x9f0a,     /* 95 */
        0x4efd,     /* 96 */
        0x0344,     /* 97 */
        0xb8fa,     /* 98 */
        0x1d8c,     /* 99 */
        0xada1,     /* 100 */
        0xe979,     /* 101 */
        0xc7d3,     /* 102 */
        0xde29,     /* 103 */
        0x6cff,     /* 104 */
        0x58b4,     /* 105 */
        0x3fd6,     /* 106 */
        0x3c1d,     /* 107 */
        0x7731,     /* 108 */
        0x007c,     /* 109 */
        0x03ae,     /* 110 */
        0x9b6a,     /* 111 */
        0x4aff,     /* 112 */
        0x42e2,     /* 113 */
        0x6e78,     /* 114 */
        0x63ed,     /* 115 */
        0xdcc8,     /* 116 */
        0xb91d,     /* 117 */
        0x9750,     /* 118 */
        0xe9b1,     /* 119 */
        0x9ca5,     /* 120 */
        0x5c60,     /* 121 */
        0x52d9,     /* 122 */
        0x72c5,     /* 123 */
        0xac5b,     /* 124 */
        0x3db4,     /* 125 */
        0x4c1b,     /* 126 */
        0x7a59      /* 127 */
    },
    /* uint16 M_dash */
    0xd217
};

/* 
 * The "lump of memory passed in initialised to R^2N mod M" needed for the
 * uint16 *A parameter for the rsa_decrypt function. This must be copied into
 * a writable array of RSA_SIGNATURE_SIZE uint16 from here before use.
 */
const  uint16 rsa_decrypt_constant_sign_r2n[RSA_SIGNATURE_SIZE] = {
    0xaaac,     /* 00 */
    0x23fe,     /* 01 */
    0x3cfa,     /* 02 */
    0xe53d,     /* 03 */
    0xd998,     /* 04 */
    0x6061,     /* 05 */
    0x2e94,     /* 06 */
    0x042a,     /* 07 */
    0x276f,     /* 08 */
    0x8c2b,     /* 09 */
    0x9f1b,     /* 10 */
    0x4b70,     /* 11 */
    0x4416,     /* 12 */
    0xab35,     /* 13 */
    0xa556,     /* 14 */
    0x17da,     /* 15 */
    0x18a1,     /* 16 */
    0x5ce7,     /* 17 */
    0x8e4d,     /* 18 */
    0x354e,     /* 19 */
    0xe173,     /* 20 */
    0x9242,     /* 21 */
    0x6844,     /* 22 */
    0x90ef,     /* 23 */
    0xbebe,     /* 24 */
    0x58ec,     /* 25 */
    0xa1e2,     /* 26 */
    0x9726,     /* 27 */
    0x9ad0,     /* 28 */
    0x3e96,     /* 29 */
    0x90d8,     /* 30 */
    0x0553,     /* 31 */
    0xe124,     /* 32 */
    0x5208,     /* 33 */
    0x8437,     /* 34 */
    0x7e57,     /* 35 */
    0x5a2b,     /* 36 */
    0x0157,     /* 37 */
    0x4874,     /* 38 */
    0x929c,     /* 39 */
    0xcf20,     /* 40 */
    0xe73f,     /* 41 */
    0x895f,     /* 42 */
    0x7583,     /* 43 */
    0x563c,     /* 44 */
    0x1696,     /* 45 */
    0x25c9,     /* 46 */
    0x2346,     /* 47 */
    0x853c,     /* 48 */
    0x8249,     /* 49 */
    0xb4fa,     /* 50 */
    0xa573,     /* 51 */
    0x1dcf,     /* 52 */
    0x0614,     /* 53 */
    0x27dc,     /* 54 */
    0x9d14,     /* 55 */
    0x2c1b,     /* 56 */
    0xb3be,     /* 57 */
    0x1030,     /* 58 */
    0xd2b2,     /* 59 */
    0xbb25,     /* 60 */
    0xa716,     /* 61 */
    0x68bd,     /* 62 */
    0x4438,     /* 63 */
    0x7e0f,     /* 64 */
    0x8479,     /* 65 */
    0x3d33,     /* 66 */
    0x62b9,     /* 67 */
    0xa070,     /* 68 */
    0xe4f6,     /* 69 */
    0x1645,     /* 70 */
    0xb9c0,     /* 71 */
    0xa9e9,     /* 72 */
    0xdacf,     /* 73 */
    0x6346,     /* 74 */
    0x9e62,     /* 75 */
    0xa224,     /* 76 */
    0x4467,     /* 77 */
    0xdbdf,     /* 78 */
    0xc2b0,     /* 79 */
    0xf110,     /* 80 */
    0xe66b,     /* 81 */
    0xfde8,     /* 82 */
    0xc474,     /* 83 */
    0xb593,     /* 84 */
    0xe805,     /* 85 */
    0xc415,     /* 86 */
    0x57ed,     /* 87 */
    0xfe87,     /* 88 */
    0xa3d6,     /* 89 */
    0xa4ed,     /* 90 */
    0x3a02,     /* 91 */
    0x3bd5,     /* 92 */
    0xedcc,     /* 93 */
    0x11f5,     /* 94 */
    0xf83c,     /* 95 */
    0x13c5,     /* 96 */
    0xa513,     /* 97 */
    0xfacc,     /* 98 */
    0xe98f,     /* 99 */
    0x25a6,     /* 100 */
    0xd3ed,     /* 101 */
    0x6c9c,     /* 102 */
    0x708b,     /* 103 */
    0x24a6,     /* 104 */
    0x5dd2,     /* 105 */
    0xb376,     /* 106 */
    0x2cc3,     /* 107 */
    0x183c,     /* 108 */
    0xe117,     /* 109 */
    0xe1a9,     /* 110 */
    0x4b6e,     /* 111 */
    0x522d,     /* 112 */
    0xbcf8,     /* 113 */
    0x8190,     /* 114 */
    0xec4b,     /* 115 */
    0x3c2a,     /* 116 */
    0x59cd,     /* 117 */
    0x56ae,     /* 118 */
    0x2e1d,     /* 119 */
    0x74bb,     /* 120 */
    0x11ad,     /* 121 */
    0xe5a6,     /* 122 */
    0x54f6,     /* 123 */
    0x5425,     /* 124 */
    0x8b88,     /* 125 */
    0xb5f4,     /* 126 */
    0xfc46      /* 127 */
};

/*
 * The value to be provided for the saltlen parameter to the 
 * ce_pkcs1_pss_padding_verify function used to decode the PSS padded SHA-256
 * hash. It has to match the value that was used in the encoding process.
 */
const unsigned long ce_pkcs1_pss_padding_verify_constant_saltlen = 222;
