/**************************************************************************/
/* Copyright (c) 2019 Qualcomm Technologies International, Ltd.           */
/* Autogenerated File, Do Not Edit                                        */
/*                                                                        */
/* This file exports public entry points from patch code                  */
/*                                                                        */
/**************************************************************************/
#ifndef SUBSYS3_PATCH0_FW0000173F_MAP_PUBLIC_H
#define SUBSYS3_PATCH0_FW0000173F_MAP_PUBLIC_H

#define PATCH_BUILD_ID                           7976

#define ENTRY_POINT_THREAD_OFFLOAD_UPDATE_P1_MEM_LOCATION 0x04002fc3 /* $_thread_offload_update_p1_mem_location */

#endif /* SUBSYS3_PATCH0_FW0000173F_MAP_PUBLIC_H */
